name = input("Enter ur name: ")
city = input("Enter ur city: ")
fav_food = input("Enter ur fav food: ")
fav_animal = input("Enter ur fav animal: ")
fav_movie = input("Enter ur fav movie name:")
fav_actor = input("fav actor: ")
fav_dog = input("fav dog: ")

print("!!! INFO!!!")
print(f'{name}')
print(f'{city}')
print(f'{fav_food}')
print(f'{fav_animal}')
print(f'{fav_movie}')
print(f'{fav_actor}')
print(f'{fav_dog}')